<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <OptimizationPreference>Speed</OptimizationPreference>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
      <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4" />
      <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4" />
      <PackageReference Include="MonoGame.ImGuiNet" Version="1.0.5" />
    </ItemGroup>

    <ItemGroup>
      <RdXmlFile Include="rd.xml" />
    </ItemGroup>

    <ItemGroup>
      <MonoGameContentReference Include="Assets/MG/MG.mgcb">
        <ContentFolder>Assets/MG</ContentFolder>
      </MonoGameContentReference>
    </ItemGroup>

    <ItemGroup>
      <Content Include="Assets/Sounds/**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>

      <Content Include="Assets/Textures/**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Assets/Blocks.toml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Artwork\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Artwork\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Artwork\**" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="find . \&#xA;  \( -type d \( -name bin -o -name obj -o -name .git -o -name .vs \) -prune \) \&#xA;  -o -type f -print &gt; file_list.txt" />
    </Target>

</Project>
