[Air]
Hardness = 0
Thickness = 0.0
MaxStack = 0
IsTransparent = true
LightEmission = 0

[Dirt]
Hardness = 2
Thickness = 0.0
MaxStack = 64
IsTransparent = false
LightEmission = 0

[Grass]
Hardness = 2
Thickness = 0.0
MaxStack = 64
IsTransparent = false
LightEmission = 0
FlipUVsHorizontally = true
FlipUVsVertically = false
FaceTextures = [
    "Grass_Side.png", # 0 - Front (-Z)
    "Grass_Side.png", # 1 - Back (+Z)
    "Grass_Side.png", # 2 - Left (-X)
    "Grass_Side.png", # 3 - Right (+X)
    "Dirt.png",  # 4 - Bottom (-Y)
    "Grass_Top.png"   # 5 - Top (+Y)
]

[Stone]
Hardness = 4
Thickness = 0.0
MaxStack = 64
IsTransparent = false
LightEmission = 0

[Sand]
Hardness = 1
Thickness = 0.0
MaxStack = 64
IsTransparent = false
LightEmission = 0

[Snow]
Hardness = 1
Thickness = 0.0
MaxStack = 64
IsTransparent = false
LightEmission = 0

[Wood]
Hardness = 3
Thickness = 0.0
MaxStack = 64
IsTransparent = false
LightEmission = 0

[Water]
Hardness = 10
Thickness = 0.5
MaxStack = 64
IsTransparent = true
LightEmission = 0

[Wisp]
Hardness = 10
Thickness = 0.5
MaxStack = 64
IsTransparent = true
LightEmission = 15

[WoodLog]
Hardness = 3
Thickness = 0.0
MaxStack = 64
IsTransparent = false
LightEmission = 0
FaceTextures = [
    "WoodLog_Side.png", # 0 - Front (-Z)
    "WoodLog_Side.png", # 1 - Back (+Z)
    "WoodLog_Side.png", # 2 - Left (-X)
    "WoodLog_Side.png", # 3 - Right (+X)
    "WoodLog_Top.png",  # 4 - Bottom (-Y)
    "WoodLog_Top.png"   # 5 - Top (+Y)
]

[Leaves]
Hardness = 1
Thickness = 0.0
MaxStack = 64
IsTransparent = true
LightEmission = 15

[Glass]
Hardness = 2
Thickness = 0.0
MaxStack = 64
IsTransparent = true
LightEmission = 0

[Feeb]
Hardness = 2
Thickness = 0.0
MaxStack = 64
IsTransparent = false
LightEmission = 15
